# Generated by Django 2.2.5 on 2019-11-05 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XxgenClaims',
            fields=[
                ('claim_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('policy_no', models.BigIntegerField()),
                ('claim_date', models.DateField(blank=True, null=True)),
                ('claim_risk', models.CharField(blank=True, max_length=200, null=True)),
                ('amount_claimed', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_setteled', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_of_settele', models.DateField(blank=True, null=True)),
                ('total_policy_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('claim_status', models.CharField(blank=True, max_length=200, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XxgenClaimsDocs',
            fields=[
                ('claim_doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('claim', models.BigIntegerField()),
                ('doc_type_code', models.CharField(blank=True, max_length=200, null=True)),
                ('doc_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XxgenClaimsProcessDtls',
            fields=[
                ('clm_process_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('claim', models.IntegerField()),
                ('policy_no', models.IntegerField()),
                ('claim_date', models.DateField(blank=True, null=True)),
                ('amount_claimed', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_setteled', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_of_settele', models.DateField(blank=True, null=True)),
                ('total_policy_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('claim_status', models.CharField(max_length=120, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XxgenClaimsSurveyorDtls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.IntegerField()),
                ('clm_survey_status', models.CharField(blank=True, max_length=200, null=True)),
                ('surveyor_comments', models.TextField(null=True)),
                ('surveyor_claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('surveyor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Masters.XxgenClaimsSurveyorMaster')),
            ],
        ),
        migrations.CreateModel(
            name='XxgenClaimsPayments',
            fields=[
                ('payment_receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_piad', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_of_piad', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Claims.XxgenClaims')),
            ],
        ),
    ]
