# Generated by Django 2.2.5 on 2019-11-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xxgenclaimsdocs',
            name='doc_type_code',
            field=models.FileField(upload_to=''),
        ),
    ]
