# Generated by Django 2.2.6 on 2019-10-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GISFAdmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
