# Generated by Django 2.2.5 on 2019-10-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GISFAdmin', '0003_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Username',
            new_name='username',
        ),
    ]
